// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonWrapper': string;
  'multiplayerTitle': string;
  'restOfBox': string;
}
declare var cssExports: CssExports;
export = cssExports;
