// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'multiplayerBox': string;
  'restOfPage': string;
  'root': string;
}
declare var cssExports: CssExports;
export = cssExports;
