// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'marked': string;
  'root': string;
  'selected': string;
  'unselectable': string;
}
declare var cssExports: CssExports;
export = cssExports;
