// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonWrapper': string;
  'online': string;
  'restOfPage': string;
  'root': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
